# Basic Settings
baseURL			= "http://138.68.49.31/"
copyright		= "Mine! Mine! Mine!"
title			= "Trantor Library" 
newContentEditor 	= "emacs"
theme 			= "nofancy"
pygmentsStyle 		= "native"
disqusshortname 	= "shimmy1996"

DefaultContentLanguage 	= "en"

[params]
	highlight	= "monokai"
	topmenu		= "categories"

[author]
	name		= "Shimmy"
	github		= "shimmy1996"
	twitter		= "shimmy1996"

[params.naviagation]
help			= "Help"

[Languages]
[Languages.en]
title			= "Trantor Library"
weight			= 1
[Languages.en.params]
github			= "github.com/shimmy1996"

[Languages.zh]
title			= "Chinese"
[Languages.zh.params]

[Languages.zh.navigation]
help			= "Aha"



