# Site Settings
baseURL                        = "https://www.shimmy1996.com/"
theme                          = ["hugo-djem-so", "hugo-hyperskip"]
footnoteReturnLinkContents     = "↩"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true
disableKinds                   = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject     = true

[author]
name = "Shimmy Xu"
email = "shimmy.xu@shimmy1996.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = false

[params]
soresuLatexOffByDefault = true
soresuIssoHost = "/isso"

[permalinks]
posts    = "/posts/:filename/"

[languages]
  [languages.en]
  languageName = "English"
  copyright    = "&copy; 2014-2020 [Shimmy Xu](/en/about/)"
  title        = "Library of Trantor"

    [[languages.en.menu.main]]
    name   = "Posts"
    url    = "/en/posts/"
    weight = 1
    [[languages.en.menu.main]]
    name   = "Friends"
    url    = "/en/friends/"
    weight = 2

  [languages.zh]
  languageName = "中文"
  copyright    = "&copy; 2014-2020 [Shimmy Xu](/zh/about/)"
  title        = "川陀大学图书室"

    [[languages.zh.menu.main]]
    name   = "归档"
    url    = "/zh/posts/"
    weight = 1
    [[languages.zh.menu.main]]
    name   = "朋友们"
    url    = "/zh/friends/"
    weight = 2