baseURL                 = "http://138.68.49.31/"
copyright               = "Mine! Mine! Mine!"
title                   = "Trantor Library" 
newContentEditor        = "emacs"
theme                   = "nofancy"
pygmentsStyle           = "native"
disqusshortname         = "shimmy1996"

DefaultContentLanguage  = "en"

[params]

[author]
name                    = "Shimmy Xu"
github                  = "shimmy1996"
twitter                 = "shimmy1996"

[Languages]
[Languages.en]
title                   = "Trantor Library"
subtitle                = "The Plan is going on."
[Languages.en.navigation]
about                   = "About"


[Languages.zh]
title                   = "川坨图书室"
subtitle                = "计划进行中。"

[Languages.zh.navigation]
about                   = "关于"



