baseURL                 = "shimmy1996.com"
title                   = "Library of Trantor"
newContentEditor        = "emacs"
theme                   = "soresu"
pygmentsStyle           = "monokai"
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
DefaultContentLanguage  = "en"
DefaultContentLanguageInSubdir = true

[permalinks]
posts = "/posts/:year/:month/:day/:slug/"

[author]
name                    = "Shimmy Xu"
github                  = "shimmy1996"
twitter                 = "shimmy1996"

[Taxonomies]
tag = "tags"
categories = "categories"

[Languages]
[Languages.en]
title                   = "Library of Trantor"
subtitle                = "The Plan is going on."
LanguageName            = "EN"

[[Languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1
[[Languages.en.menu.main]]
    name = "Posts"
    url = "/en/posts/"
    weight = 2
[[Languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 3
[[Languages.en.menu.main]]
    name = "Friends"
    url = "/en/friends/"
    weight = 4
[[Languages.en.menu.main]]
    name = "Messages"
    url = "/en/messages/"
    weight = 5

[Languages.zh]
title                   = "川陀大学图书室"
subtitle                = "计划进行中。"
LanguageName            = "中文"

[[Languages.zh.menu.main]]
    name = "主页"
    url = "/zh/"
    weight = 1
[[Languages.zh.menu.main]]
    name = "归档"
    url = "/zh/posts/"
    weight = 2
[[Languages.zh.menu.main]]
    name = "关于"
    url = "/zh/about/"
    weight = 3
[[Languages.zh.menu.main]]
    name = "朋友们"
    url = "/zh/friends/"
    weight = 4
[[Languages.zh.menu.main]]
    name = "留言板"
    url = "/zh/messages/"
    weight = 5