# Site Settings
baseURL                        = "shimmy1996.com"
theme                          = "soresu"
footnoteReturnLinkContents     = "↩"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true
preserveTaxonomyNames          = true

# Pygments Settings
pygmentsCodefences             = true
pygmentsCodefencesGuessSyntax  = false
pygmentsStyle                  = "emacs"
pygmentsOptions                = "linenos="

[Permalinks]
posts    = "/posts/:year-:month-:day-:slug/"

[Taxonomies]
category = "categories"
tag      = "tags"

[Languages]
  [Languages.en]
  languageName = "EN"
  copyright    = "&copy; [Shimmy Xu](/en/contact/) 2017-2018 | [Github](https://github.com/shimmy1996) | [Keybase](https://keybase.io/shimmy1996) | [Mastodon](https://mstdn.shimmy1996.com/@shimmy1996) | [Subscribe](/en/index.xml)"
  subtitle     = "The Plan is going on."
  title        = "Library of Trantor"

    [Languages.en.taxonomy]
    categories = "Categories"
    tags       = "Tags"

    [[Languages.en.menu.main]]
    name   = "Home"
    url    = "/en/"
    weight = 1
    [[Languages.en.menu.main]]
    name   = "Posts"
    url    = "/en/posts/"
    weight = 2
    [[Languages.en.menu.main]]
    name   = "About"
    url    = "/en/about/"
    weight = 3
    [[Languages.en.menu.main]]
    name   = "Friends"
    url    = "/en/friends/"
    weight = 4

  [Languages.zh]
  languageName = "中文"
  copyright    = "&copy; [Shimmy Xu](/zh/contact/) 2017-2018 | [Github](https://github.com/shimmy1996) | [Keybase](https://keybase.io/shimmy1996) | [Mastodon](https://mstdn.shimmy1996.com/@shimmy1996) | [订阅](/zh/index.xml)"
  subtitle     = "计划进行中。"
  title        = "川陀大学图书室"

    [Languages.zh.taxonomy]
    categories = "分类"
    tags       = "标签"

    [[Languages.zh.menu.main]]
    name   = "主页"
    url    = "/zh/"
    weight = 1
    [[Languages.zh.menu.main]]
    name   = "归档"
    url    = "/zh/posts/"
    weight = 2
    [[Languages.zh.menu.main]]
    name   = "关于"
    url    = "/zh/about/"
    weight = 3
    [[Languages.zh.menu.main]]
    name   = "朋友们"
    url    = "/zh/friends/"
    weight = 4