# Site Settings
baseURL                        = "https://www.shimmy1996.com"
relativeURLs                   = true
theme                          = ["hugo-ataru", "hugo-hyperskip"]
footnoteReturnLinkContents     = "↩"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true
disableKinds                   = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject     = true
hasCJKLanguage                 = true

[author]
name = "Shimmy Xu"
email = "shimmy.xu@shimmy1996.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = false

[params]
soresuLatexOffByDefault = true
soresuIssoHost = "/isso"

[permalinks]
posts    = "/posts/:filename/"
hoots    = "/hoots/:filename/"

[languages]
  [languages.en]
  languageName = "English"
  copyright    = "&copy; 2014&ndash;2020 [Shimmy Xu](/en/about/)"
  title        = "Library of Trantor"
  summaryLength = 50

    [[languages.en.menu.main]]
    name   = "Timeline"
    url    = "/en/"
    weight = 1
    [[languages.en.menu.main]]
    name   = "Posts"
    url    = "/en/posts/"
    weight = 2
    [[languages.en.menu.main]]
    name   = "Hoots"
    url    = "/en/hoots/"
    weight = 3


  [languages.zh]
  languageName = "中文"
  copyright    = "&copy; 2014&ndash;2020 [Shimmy Xu](/zh/about/)"
  title        = "川陀大学图书室"
  summaryLength = 25

    [[languages.zh.menu.main]]
    name   = "时间线"
    url    = "/zh/"
    weight = 1
    [[languages.zh.menu.main]]
    name   = "日志"
    url    = "/zh/posts/"
    weight = 2
    [[languages.zh.menu.main]]
    name   = "鸮文"
    url    = "/zh/hoots/"
    weight = 3