baseURL                 = "http://138.68.49.31/"
copyright               = "Mine! Mine! Mine!"
title                   = "Library of Trantor" 
newContentEditor        = "emacs"
theme                   = "soresu"
pygmentsStyle           = "monokai"
disqusshortname         = "shimmy1996"
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
DefaultContentLanguage  = "en"
DefaultContentLanguageInSubdir = true

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[author]
name                    = "Shimmy Xu"
github                  = "shimmy1996"
twitter                 = "shimmy1996"

[Languages]
[Languages.en]
title                   = "Trantor Library"
subtitle                = "The Plan is going on."
LanguageName            = "EN"

[Languages.en.params]
description = "The greatest library ever."

[Languages.en.navigation]
about                   = "About"

[[Languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1
[[Languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[Languages.en.menu.main]]
    name = "Posts"
    url = "/en/post/"
    weight = 3
[[Languages.en.menu.main]]
    name = "Tags"
    url = "/en/tags/"
    weight = 4
[[Languages.en.menu.main]]
    name = "Categories"
    url = "/en/categories/"
    weight = 5
[[Languages.en.menu.main]]
    name = "Friends"
    url = "/en/friends/"
    weight = 6
[[Languages.en.menu.main]]
    name = "Messages"
    url = "/en/messages/"
    weight = 7

[Languages.zh]
title                   = "川坨图书室"
subtitle                = "计划进行中。"
LanguageName            = "中文"

[Languages.zh.navigation]
about                   = "关于"

[Languages.zh.params]
description = "最伟大的图书馆。"

[[Languages.zh.menu.main]]
    name = "主页"
    url = "/zh/"
    weight = 1
[[Languages.zh.menu.main]]
    name = "关于"
    url = "/zh/about/"
    weight = 2
[[Languages.zh.menu.main]]
    name = "归档"
    url = "/zh/post/"
    weight = 3
[[Languages.zh.menu.main]]
    name = "标签"
    url = "/zh/tags/"
    weight = 4
[[Languages.zh.menu.main]]
    name = "分类"
    url = "/zh/categories/"
    weight = 5
[[Languages.zh.menu.main]]
    name = "朋友们"
    url = "/zh/friends/"
    weight = 6
[[Languages.zh.menu.main]]
    name = "留言板"
    url = "/zh/messages/"
    weight = 7
