# Site Settings
baseURL                        = "https://www.shimmy1996.com/"
theme                          = "hugo-soresu"
footnoteReturnLinkContents     = "↩"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true
preserveTaxonomyNames          = true

# Pygments Settings
pygmentsCodefences             = true
pygmentsCodefencesGuessSyntax  = false
pygmentsOptions                = "linenos="
pygmentsUseClasses             = true

[Blackfriday]
smartypants = false

[params]
soresuLatexOffByDefault = true
soresuIssoHost = "/isso"

[Permalinks]
posts    = "/posts/:year-:month-:day-:slug/"

[Taxonomies]
category = "categories"
tag      = "tags"
serie    = "series"

[Languages]
  [Languages.en]
  languageName = "English"
  copyright    = "&copy; 2014-2019 [Shimmy Xu](/en/about/) | <a rel=\"me\" href=\"https://github.com/shimmy1996\">GitHub</a> | <a rel=\"me\" href=\"https://mstdn.shimmy1996.com/@shimmy1996\">Mastodon</a> | [Subscribe](/en/index.xml)"
  title        = "Library of Trantor"

    [[Languages.en.menu.main]]
    name   = "Home"
    url    = "/en/"
    weight = 1
    [[Languages.en.menu.main]]
    name   = "Posts"
    url    = "/en/posts/"
    weight = 2
    [[Languages.en.menu.main]]
    name   = "Friends"
    url    = "/en/friends/"
    weight = 3

  [Languages.zh]
  languageName = "中文"
  copyright    = "&copy; 2014-2019 [Shimmy Xu](/zh/about/) | <a rel=\"me\" href=\"https://github.com/shimmy1996\">GitHub</a> | <a rel=\"me\" href=\"https://mstdn.shimmy1996.com/@shimmy1996\">Mastodon</a> | [订阅](/zh/index.xml)"
  title        = "川陀大学图书室"

    [[Languages.zh.menu.main]]
    name   = "主页"
    url    = "/zh/"
    weight = 1
    [[Languages.zh.menu.main]]
    name   = "归档"
    url    = "/zh/posts/"
    weight = 2
    [[Languages.zh.menu.main]]
    name   = "朋友们"
    url    = "/zh/friends/"
    weight = 3

    [Languages.zh.Blackfriday]
    extensions = ["joinLines"]
    smartypants = false
