# Site Settings
baseURL                        = "https://www.shimmy1996.com"
relativeURLs                   = true
theme                          = ["hugo-ataru", "hugo-hyperskip"]
footnoteReturnLinkContents     = "↩"
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true
disableKinds                   = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject     = true
hasCJKLanguage                 = true

[author]
name = "Shimmy Xu"
email = "shimmy.xu@shimmy1996.com"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.comments]
    baseName = "comments"
    mediaType = "application/atom+xml"

[outputs]
  home = ["HTML", "RSS", "COMMENTS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = false

[params]
webmentionEndpoint = "https://webmention.io/www.shimmy1996.com/webmention"

[permalinks]
posts    = "/posts/:filename/"
hoots    = "/hoots/:filename/"

[languages]
  [languages.en]
  languageName = "English"
  copyright    = "&copy; 2014&ndash;2020 Shimmy Xu"
  title        = "Library of Trantor"
  summaryLength = 50

    [[languages.en.menu.main]]
    name   = "Timeline"
    url    = "/en/"
    weight = 1
    [[languages.en.menu.main]]
    name   = "Posts"
    url    = "/en/posts/"
    weight = 2
    [[languages.en.menu.main]]
    name   = "Hoots"
    url    = "/en/hoots/"
    weight = 3

  [languages.zh]
  languageName = "中文"
  copyright    = "&copy; 2014&ndash;2020 Shimmy Xu"
  title        = "川陀大学图书室"
  summaryLength = 25

    [[languages.zh.menu.main]]
    name   = "时间线"
    url    = "/zh/"
    weight = 1
    [[languages.zh.menu.main]]
    name   = "日志"
    url    = "/zh/posts/"
    weight = 2
    [[languages.zh.menu.main]]
    name   = "鸮文"
    url    = "/zh/hoots/"
    weight = 3

  # [languages.ja]
  # languageName = "日本語"
  # copyright    = "&copy; 2014&ndash;2020 Shimmy Xu"
  # title        = "トランター大学図書室"
  # summaryLength = 25

  #   [[languages.ja.menu.main]]
  #   name   = "タイムライン"
  #   url    = "/ja/"
  #   weight = 1
  #   [[languages.ja.menu.main]]
  #   name   = "記事"
  #   url    = "/ja/posts/"
  #   weight = 2
  #   [[languages.ja.menu.main]]
  #   name   = "ツイート"
  #   url    = "/ja/hoots/"
  #   weight = 3