#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: ./posts
#+OPTIONS: author:nil

* My Life                                                          :@my_life:
** TODO 2018 in Review                                                :plans:
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :date 2019-01-03 :slug 2018-in-review
:END:

*** DONE en
:PROPERTIES:
:EXPORT_TITLE: 2018 in Review
:EXPORT_FILE_NAME: 2019-01-03-2018-in-review.en.md
:END:

Before anything, happy New Year!

It's an interesting feeling when the time span of one year gradually becomes
shorter relative to the time that has already passed in one's life. If only the
actual length of one year also scales with one's age, perhaps we would feel more
of the excitement instead of anxiety during the New Year count down. That being
said, 2018 was a lot of fun for me, even without ray-tracing graphic cards.

**** The Amazing 2018
To quote my 2017 self:

#+BEGIN_QUOTE
If I've learned anything from my past failed plans, it would be to always
underestimate my own capabilities when planning...
#+END_QUOTE

Yeah, it's totally just that my estimates about the amount of free time I would
have was off, as can be seen from the status of my 2018 goals.

- [ ] Run 1000 miles. [405/1000]
- [ ] Finish a marathon.
- [ ] Write 20 blog posts. [10/20]
- [ ] Get the first signature for my PGP key.
- [ ] Install Gentoo.

Knowing that I can always change the 'publish date' of blog entries (thanks to
=hugo=), I grew into the bad habit of starting an article and just then shelving
it for months to come. When I finally remember that one unfinished article, I
frequently dismiss the idea as not really worth elaborating. Now that I think
about it, maybe this is exactly what blogs are for, providing a snapshot of
myself that I can look back later, whether my future self find it silly or 'not
really worth elaborating'.

The number of movie theater visits I had in 2018 probably accounts for 50% of my
lifetime total, and with double doses of disappointment from /Star Wars: The
Last Jedi/ and /Incredibles 2/. By the way, 2018 also saw 90% of my lifetime
popcorn consumption. I've never realized those can be such addicting.

Although not a marathon, I did ran my first trail half marathon in May. It was
the first time I've ever hit the wall while running, due to bad pacing and
unpreparedness for the weather. The race started mid afternoon on a scorchingly
hot day. After witnessing quite a few people stopped to walk in the first 2
miles, I started off quite a bit faster than my intended pace fueled by a stupid
sense of superiority, and hit the wall right at the mark of 4 miles. Fortunately
the feeling faded away as I walked the next half of the race, gulping ice-cold
Gatorade at every hydration point. However, the ice-cold Gatorade was another
trap -- temperature dropped rapidly as sun started to set and my stomach started
to complain about all the chilly liquid. As the finish line appeared within 400
meters of my sight, my legs were hit by the strongest cramps I've ever
had. After barely making it through while being surpassed by 3 people right
before finish line, I could only be happy to learn that I was still not the last
one: actually, I'm even the first one in my age group (+whose size is one+). The
somewhat illegitimate feeling of compliment, mixed with a bit of salt and guilt
made the race a wondrous experience.

**** The Spectacular 2019
Since Google is deprecating Inbox in the coming March, I've lost my last excuse
for clinging to Gmail. I'll try to gradually fade out my Gmail usage for my own
email server.

On the front of searching for best solution for blog comments, quite a few
bloggers I follow have started embracing the [[https://indieweb.org/][IndieWeb]] and [[https://webmention.net/][Webmention]]
standards. In a lot of ways, Webmention was the exact thing I wanted: federated
blog comments, posts, and more. Yet I'm reluctant to move further away from a
static site, not to mentioning most easy-to-follow Webmention solutions I have
found relies heavily on third-party services. The IndieWeb standard though is
fairly intriguing. I've never had much use for [[https://keybase.io/][Keybase]] aside from it being a hub
linking most of my online presences (decryption and encryption does not work
without uploading PGP private keys, and I have no one to securely chat with),
perhaps I should just replace it with =rel=me= links.

Diving into C++17 was fairly enjoyable during the past year, so I'm looking into
learning other new programming languages. [[https://www.rust-lang.org/][Rust]] and [[https://julialang.org/][Julia]] have been on my radar
for a while, especially Rust. Having a full suite of officially supported tools
makes writing Rust a smooth and deeply satisfying experience. I'll try to dive
deeper into both languages and hopefully put them into some uses.

As for running and blog posts, I'll try to match 2018's numbers. On top of
those, I'm thinking about keeping a record of the books, music, and shows I've
read/listened/watched on this blog, along with my thoughts. I actually attempted
something similar during this blog's Wordpress days: I once setup a MediaWiki
instance for similar purposes, but lacked the motivation to continue maintaining
the entries. I'll keep it simple this time, and I should come up with a set of
rating system.

What should I do with the remaining 2018 goals? A separate wishlist is a pretty
good idea -- let's go with that. As a stretch goal, I should probably clean my
desktop computer, which is stuffed with four-year-old dirt, cat hair, and dead
skin cells.

Here's to another spectacular 2.9e+17 radiation periods of Caesium-133!

*** TODO zh
:PROPERTIES:
:EXPORT_TITLE: 回顾 2018
:EXPORT_FILE_NAME: 2019-01-03-2018-in-review.zh.md
:END:

* Geekery                                                          :@geekery:
** TODO Installing Gentoo                                             :linux:
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :date 2019-01-27 :slug installing-gentoo
:END:

*** DONE en
:PROPERTIES:
:EXPORT_TITLE: Installing Gentoo
:EXPORT_FILE_NAME: 2019-01-27-installing-gentoo.en.md
:END:

I finally bite the bullet and installed Gentoo on VirtualBox (totally not motivated by the front page wishlist), thereby achieving my ultimate digital @5c3n510n (or descent according to DistroWatch).

Jokes aside, the installation process is surprisingly pleasant: the [[https://wiki.gentoo.org/wiki/Handbook:Main_Page][Gentoo Handbook]] is wonderfully written, and seems to have a plan for everything that might go wrong. I like the Handbook more than ArchWiki's [[https://wiki.archlinux.org/index.php/Installation_guide][Installation Guide]] as it also details the rationale behind each step I took, which is often a fun read in its own right. I would go as far as saying the Gentoo Handbook is actually more beginner friendly, as it carefully assembles bits of information that are normally scattered all over the place, providing a great starting point for learning how to tame the operating system. Besides, Gentoo Handbook covers more than installation: it also contains other necessary setup processes to set up a usable system. I will be gradually replicating my current desktop setup to decide if a migration is worth the time.

My very first encounter with GNU/Linux operating systems is Ubuntu 12.04: one of my classmates (vacuuny/A2Clef) was installing it in school's computer labs. There was a time when I would switch between various Ubuntu variants every few days. I dual booted Windows and Ubuntu for a while before switching entirely to Ubuntu in 2014. Much annoyed by the Amazon ads, I tried out Arch Linux as part of my New Year's resolution in 2015. Even with a second computer to look up instructions, it still took me quite a while to adapt to the new system. I ranted "maybe I still haven't gotten the Arch way" in my old blog, but never looked back once I got the knack of it.

I still try out other distributions from time to time in VirtualBox, but never find them to offer much improvements compared with Arch beyond the setup processes, and even more so when considering the excellent documentation on ArchWiki (well now we have a contender). Once I have my desktop environment set up, the experience between distributions is not that different, but the distinctions kicks in when problems occur and I search online for troubleshooting tips. Having more up-to-date packages is another charm Arch has. More recently, the =systemd= controversy caused me to start shopping around for a new distribution to try out, not so much because of the actual security concerns, but just to see what it is like to use different init system: I mostly used GUI under Ubuntu (=apt-get= and =nano= was probably the only command I knew for the longest time) and Arch was already using =systemd= when I switched. Aside from Gentoo, the candidates include Void Linux and the BSDs. Void Linux was easy to set up with its installer wizard, yet I didn't feel compelled to move to it. Let's see if Gentoo would change my mind.

* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables: fill-column: 80 eval: (auto-fill-mode nil) eval: (add-hook
# 'after-save-hook #'org-hugo-export-subtree-to-md-after-save :append :local)
# End:
