#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+OPTIONS: author:nil
#+STARTUP: fninline

* DONE 2019 in Review
:PROPERTIES:
:EXPORT_DATE: 2020-01-01
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :slug 2019-in-review
:END:

** DONE en
:PROPERTIES:
:EXPORT_TITLE: 2019 in Review
:EXPORT_FILE_NAME: 2020-01-01-2019-in-review.en.md
:END:

Each New Year feels incrementally less special (see the relative length argument I wrote in review of 2018), although as an end to the laziness-inducing and overly noisy holiday season, having festival associated with new goals and resolutions is not too bad an idea.

Looking at the number 2020 does give me a bit more excitement as it always felt like such a distant time in the future: I don't even remember any sci-fi works referencing anything in the 2020s, as most of them either stopped at the 2010s or go way beyond to the 3000s. This new decade is stuck in what I call, an expectation limbo. Oh, fun fact from [[https://en.m.wikipedia.org/wiki/2020][Wikipedia]], 2020 will also see the beginning of the year of Metal Rat in Chinese calendar - such a punk name for a something rather traditional.

*** 2019 Rewind
I'm glad to announce that everything went according to plan in 2019!

- ☑ Run 400 miles. [555/400]
- ☑ Write 10 blog posts. [14/10]
- ☑ Stop using Gmail/Inbox app. [2/2]
- ☑ Add =rel=me= links to blog.
- ☑ Dive into Rust and Julia. [2/2]
- ☑ Record books, music, and shows I enjoyed.
- ☑ Clean my desktop computer.

With some uncertainties in my life sorted out, I've been following my daily routines a lot better in 2019. I still procrastinate on blog posts from time to time, but at least I'm also publishing ever so more often. Learning Rust and Julia was fun, and I did get some uses out of them in real projects. I also attempted Advent of Code in both languages and got to the day 17 before each day's questions started taking too much time. I thought about finishing all the remaining ones after Christmas, but decided against it - I don't see myself learning more about the languages through these questions and the time could be better spent elsewhere.

I gave the blog a face-lift, writing a new Hugo theme in the process, with [[https://getkiss.org/blog/20191004a][this article]] serving as an inspiration. I find the process of eliminating all the nice-to-haves and bells-and-whistles oddly satisfying: I enjoy having my blog as a lean, mean, killing machine. The website feed has been updated to use ATOM, with each post displayed in its entirety instead of the default broken summary. I started using web feeds for reading blogs after failing miserably at my last attempt to organize my web browser bookmarks and I've enjoyed it so far.

I went to the movies three times this year, for /Dragon Ball Super: Broly/, /Promare/, and /Star Wars: The Rise of Skywalker/, and I mostly enjoyed my time in all three occasions: trying to quantify this enjoyment using a rating is probably not doing them justice, as I enjoyed the three for vastly different reasons. Since I visit the theaters so scarcely, the time I spend on airplanes actually account for a large portion of my movie consumption, and /Spider-Man: Into to the Spider-Verse/ was the stand out among those I watched while flying. On Christmas Eve, instead of /Toradora!/, an tradition of mine during college, I rewatched /Scott Pilgrim vs. the World/, which I also first saw on a flight years ago, and it was as geird (Good but in a weird way and weird but in a good way, like, you know, goodd? This is not a real word yet, but who cares? It's year of Metal Rat!) as I remembered.

As someone that have always lived at places that never snow until 2018, snow to me is such a distant concept that I'd consider any movie with snow scenes a Christmas movie. Even after moving to a snowing city mid 2018, I still haven't seen the stereotypical fluffy Christmas snow that almost seem warm to the touch: all I got were piles of dirty water-ice compound on roadsides (oh and they find their way into your shoes too) that reminds me more of fish market than Christmas. Meh, I bet all those snow in the movies are just props, just like the Moon landing.

Back in 2018, I set up a Mastodon instance, and I have since deleted my twitter account, but I never use Mastodon that much. At first I thought it's just that I'm not the microblogging type, but now I beginning think it's all the cognitive overhead of logging in, editing, tagging, and translating that made posting a status update rather daunting for me. I have been microblogging in [[https://twtxt.readthedocs.io/en/latest/][twtxt]] format for the last few months of 2019 and I did rack up a considerable status count (all 110 of them). Being one command away from dumping whatever silly one-liner I have in mind is quite addicting, and revisiting the twtxt file also gives me new post ideas at times. Separating a Twitter-like social media service into read-only (with feed reader), write-only (what I use twtxt for), and interactive (still figuring that one out) parts simply works better for me. My twtxt file will likely replace Mastodon in the footer this year, as keeping a behemoth (just one more pun, please?) of a web app happy and running has not been exactly pleasant for me.

Speaking of deleting accounts, I've setup forwarding from all my Gmail accounts to my self-hosted email and all my devices are Gmail and Inbox (RIP) free now. I'm still not quite ready to completely ditch the Google accounts yet, but I'm getting closer: I've been trying out registrars other than Google Domains, and using Youtube's built-in web feeds instead of relying on subscriptions. I did finally remove my Facebook account though, and the account purge will likely continue.

*** Road to 2020
Since it worked out really well for 2019, I'll continue to match previous year's numbers on blog posts and running. Donuts have been my guilty pleasure late night in 2019 (thanks to Dunkin'), and it's one of the few kinds of food I still willingly consume despite the detrimental effect to my health. Thus, no donuts in 2020, not under my watch!

I do want to set up a proper data backup workflow, following 3-2-1 strategy and all that. As for new languages to learn, Go has been creeping on my radar for a while and with the release of Go modules, it seems like the right time to jump in. There's also C++20 on the horizon.

2020 will also see the release of several Linux phones (Librem 5 and PinePhone), and I'm more than willing to try some of them out and explore ways of escaping the Apple ecosystem. PineTime, on the other hand, might be the perfect replacement for my aging Pebble Time Round.

Out side of technical ones, I haven't read any books in quite a while, at least not those that can be classified as proper literature, and I seek to change that in 2020.

Here's to the end of Skywalker saga, and whatever comes after generation Z!

** DONE zh
:PROPERTIES:
:EXPORT_TITLE: 回顾 2019
:EXPORT_FILE_NAME: 2020-01-01-2019-in-review.zh.md
:END:

每个新年给我带来的新鲜感都不断地下降（参见我在回顾 2018 时提到的一年的相对长度），不过用一个和新的目标与决心绑定的节日来结束过于嘈杂且让人感到慵懒的假日季节并不是一个坏主意。

话说回来，看到 2020 这个数字会让人不自觉地感到兴奋，因为这在我的印象里总是存在于极为遥远的未来：我甚至不记得任何描绘 2020 年代的科幻作品。大多数作品不是止于 2010 年代，就是直接跳到 31 世纪，使得接下来的十年处于期待值的空白区域。对了，2020 年将迎来农历的庚子年，而有趣的是 [[https://en.m.wikipedia.org/wiki/2020][维基百科]] 的英文直译是“金属耗子”——想不到一个传统概念会有这么朋克的名称。

*** 2019 回放
2019 年的计划进行的非常顺利！

- ☑ 跑 400 英里。[555/400]
- ☑ 写 10 篇日志。[14/10]
- ☑ 停止使用 Gmail 、 Inbox 应用程序 。[2/2]
- ☑ 给博客加上 =rel=me= 链接。
- ☑ 进一步了解 Rust 和 Julia 。 [2/2]
- ☑ 记录我中意的书籍，音乐，和影视作品。
- ☑ 清理台式电脑。

在排除了生活中的一些不确定因素后，我在 2019 年的日常变得更更规律了。我仍然时不时地拖延博客文章，但至少发布日志的频率高了一些。学习 Rust 和 Julia 很有趣，而且我也在实际项目中用到了它们。我还尝试了用这两种语言完成 Advent of Code 并撑到了第17天，到解决问题所需时间太长为止。我曾考虑过圣诞节后完成所有剩余的问题，但我决定不这样做——我认为自己不会通过这些问题增加对这些语言的了解，把时间花在其他地方可能会更好。

受到 [[https://getkiss.org/blog/20191004a][本文]] 启发，我给博客写了一个新的 Hugo 主题。我发现一步步消除那些可有可无的装饰的过程奇怪地令人满足：我希望博客带有任何不必要的东西。本站的订阅源已改为使用ATOM，并且完整显示每篇日志，而不是默认的支离破碎的摘要。在上一次尝试整理浏览器书签并遭遇惨败后，我开始使用网站订阅源来阅读其他博客。到目前为止，我很喜欢这一新方式。

我今年去电影院看了三部电影，分别是《龙珠超：布罗利》，《普罗米亚》和《星球大战：天行者的崛起》。三次观影都还算愉快：试图用评级来量化这种享受可能并不公平，因为我喜欢每一部电影的原因都不尽相同。由于我很少去电影院看电影，我在飞机上度过的时间贡献了我电影消费的很大一部分。《蜘蛛侠：平行宇宙》是我 2019 在飞机上看的影片里最好的一部。在圣诞夜，我没有延续大学期间的传统——看《龙与虎》，而是重温了一部我在数年前的一次飞行中看的电影，《歪小子斯科特》。这部电影的确像我记忆中的那样怪趣。

作为一个直到 2018 年都住在不会下雪的地方的人，雪对我来说是一个如此陌生的概念，以至于我会把任何有下雪场景的电影都视为圣诞节电影。即使在 2018 年年中搬到一个下雪的城市之后，我仍然没有看到过那种虽然俗套、但蓬松得似乎带有温度的圣诞雪：我所住的地方只有堆积在路边的脏水和脏冰的混合物（而且它们总能找到办法进入你的鞋子）。这更能让我想到鱼市而非圣诞节。我敢打赌，电影中所有的积雪场景都只是道具，就像登月照片一样。嗯，肯定是这样。

在 2018 年，我设置了一个 Mastodon 实例，此后我删除了自己的 Twitter 帐户，但是我并不经常使用 Mastodon 。起初我觉得我属于不会写微型博客的类型，但是现在我开始认为是登录、编辑、加标签和翻译的认知开销导致了我不怎么热衷于更新状态。在 2019 年的最后几个月里，我一直在用 [[https://twtxt.readthedocs.io/en/latest/][twtxt]] 格式发布微型博客，并积累了相当数量的博文（110条）。当发布我脑海里的任何愚蠢的想法都只有一行命令之遥时，写微型博客还是挺让人上瘾的，并且重新访问 twtxt 文件有时还会给我带来新的日志想法。将一个类似 Twitter 的社交媒体服务分为只读（订阅源阅读器）、只写（也就是我使用 twtxt 的目的）和互动（我还没有很好的解决办法）的部分对我来说更加合适。我的 twtxt 文件今年很可能会取代页脚里的 Mastodon 链接，因为维持这个重量级网络应用的日常运行对我来说并不是件愉快的事情。

说到删除帐户，我已经将我所有的 Gmail 帐户设为自动转发到我自己架设的电子邮箱，并且我所有的设备现在都已经没有了 Gmail 和 Inbox（RIP）应用。 我还没有做好完全放弃 Google 帐户的准备，但是我已经比之前更接近了：我在尝试使用除 Google Domains 以外的其他注册服务商，并使用 Youtube 内置的订阅源而非依赖订阅频道来获取更新信息。不过我成功删除了我的 Facebook 帐户。帐户清理还会继续下去。

*** 2020 之路
由于这个办法在 2019 年效果很好，因此我将继续在博客文章和跑步里程上尝试与去年的数字保持一致。 甜面包圈常常是我在 2019 年深夜里罪恶感的来源（都是 Dunkin' 的错）。甜面包圈是为数不多的几种尽管会给健康带来不利影响但我仍然愿意食用的食物之一，所以我在此宣言： 2020 年不会有甜面包圈！

我一直都想正式建立起一套遵循 3-2-1 原则的数据备份流程。至于要学习的新语言，我已经注意 Go 有一段时间了。随着 Go 模块的发布，这似乎是一个合适的开始时机。除此之外，还有即将到来的 C++20 。

2020 年会有几种不同的 Linux 手机（ Librem 5 和 PinePhone ）发布。我很乐意尝试它们，以探索离开 Apple 生态系统的方法。另一方面，PineTime 可能是我已逐渐老化的 Pebble Time Round 的完美替代品。

除了技术性的之外，我已经有一段时间没有阅读任何书籍了，至少没有任何足以被称为文学作品的书籍。我想在 2020 年改变这种状况。

为天行者系列的终结以及我很好奇会被如何命名的 Z 世代之后出现的一代干杯！

* TODO Staring at Yesterday in One Eye
:PROPERTIES:
:EXPORT_DATE: 2020-01-06
:EXPORT_HUGO_SLUG: staring-at-yesterday-in-one-eye
:END:

** DONE en
:PROPERTIES:
:EXPORT_FILE_NAME: 2020-01-06-staring-at-yesterday-in-one-eye.en.md
:EXPORT_TITLE: Staring at Yesterday in One Eye
:END:

The dead speak! The galaxy has heard a mysterious broadcast, a record of *THE PAST* in the familiar yet distant tone of *MY OLD SELF*.

*** A Link to the Past
Alright, that's enough puns and /The Rise of Skywalker/ jokes from me. As mentioned before, my blog was originally using WordPress and switched to Hugo in 2017-09-01. To be more specific, I actually had two WordPress blogs: one named Pandora (because of Borderlands 2, but this is such an cliche name that I'm sure there's a million other imaginary planets using this name) hosted with WordPress.com, and another being Library of Trantor (because of Isaac Asimov's /Foundation/ series) hosted on Bluehost, with the former written in English and latter in Chinese. Since I kept archives of both before taking them down, I was able to revive all those old posts from the grave using [[https://github.com/SchumacherFM/wordpress-to-hugo-exporter][this tool]] and some elbow grease.

Handling images is tricky and my old posts made quite liberal uses of them unfortunately: I opted for the simplest way out and just kept the originals without any kind of fancy compression or styling. I still need to figure out a more efficient way to both store and serve those images. Even with Git LFS available, I was reluctant to add all 300+ Megabytes of images to my blog repository (so they are currently in untracked-land), and now my blog could definitely benefit from a CDN setup unless I find an efficient way to compress all of them (maybe do what Jupyter notebooks do: encode images in base64 to get a single HTML file).

Through out the years, I've used WordPress, Disqus, Duoshuo (now defunct), and Isso as my comment systems. Now, my [[https://git.shimmy1996.com/shimmy1996/hugo-hyperskip][Hyperskip]] has superseded them all: it's the one true static comment system to end all comment systems! Taking inspiration from [[https://staticman.net/][Staticman]], I also store all the comments as a TOML file, but opted to use email as submission method, making the process much easier. Gone are the days of databases, queries, and external scripts, and I get to version control all the comments in the same Git repository as my blog. The ongoing search for the ideal commenting system is finally over for me (until it starts again).

I refrained myself from leaving out any of the old posts, as the main motivation of this effort is really just to be able to easily see and be reminded of my older self. It's a strange yet familiar experience reading those old writings: I can see parts of me that has changed and parts that are still distinctively =shimmy1996=.

*** The Other Old Friend
One week into the New Year and I have already switched color scheme of the website five times, with another twenty sitting in my folder (totally not because of how unsightly these RGB color codes are). Much like how I'm a bit burned out from trying to [[/en/posts/2019-12-01-fun-with-fonts-on-the-web/][get fonts right for everything]], I have decided to remove all custom color choices from the website: no syntax highlighting, no fancy buttons, and no dark modes.

Tags and categories are gone, too. As long as there are little knobs that I can play around with, I always find myself distracted and spending way too much time worrying about the most insignificant choice of words, colors, or spacing (as you can tell by how much of I blog about the blog). The only cure I found is to simply remove the opportunities of making those choices altogether, and stick with the default.

Completely contrast to how the saying normally goes, I hardly ever find myself missing the things I cut away. More often than not, I sympathize with the elephant that finally broke free from the rope, rather than feeling the emptiness for losing something cherished. What if maintaining all those babbling by my past self is just another such rope holding me back that I just haven't realized yet? Well, I could always use a spare coil of paracord and an old friend on the road.
