#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+OPTIONS: author:nil
#+STARTUP: fninline logdone

* TODO 2020 in Review
:PROPERTIES:
:EXPORT_DATE: 2021-01-01
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :slug 2020-in-review
:END:

** DONE en
CLOSED: [2021-01-01 Fri 10:07]
:PROPERTIES:
:EXPORT_TITLE: 2020 in Review
:EXPORT_FILE_NAME: 2021-01-01-2020-in-review.en.md
:END:

Rooftops are all covered in patches of white this morning. All the billboards have lost their typical splendor to the gloomy sky. Even the street lamps' orange glow failed to add any warmth to the car-less roads. Spots of light from a handful of building windows, however, do appear extra dazzling.

What a year. It feels like space-time has a higher viscosity than usual—dense enough to reduce sunlight to just an ivory ambiance—given how eventful the past 300-or-so days have been.

I'm actually glad that the first day of 2021 still very much feels like any day in 2020. Not very much should physically change simply because of a number flip, not to mention a rather arbitrary one, but perhaps it's exactly for the lack of change that we need to forge something new, something that gives an adrenaline kick, no matter how small.

Ugh, fine. I see no harm in giving in to this cheap psychological trick every once in a while.

Happy New Year, we made it.

*** 2020: Apocalypse
I'm not cutting myself any more slacks this time around.

- ☑ +Run 550 miles.+ Run 205 miles and cycle 865 miles (2.5x). [205/205][872/865]
- ☑ Write 14 blog posts. [16/14]
- ☑ No donuts.
- ☐ Dive into Go and C++20. [1/2]
- ☐ Set up proper backup workflow.
- ☐ Read non-technical books.

Because of COVID-19, I have stopped running outdoors since early March. After a few months of hiatus, I got a bike and a trainer in June and started cycling indoors instead. The 2.5x scaling factor is based on the mileage I can cover in around the same time. Working out in a more controlled environment is very enjoyable. Aside from easy access to fueling and shielding from the weather, being able to watch anime/listen to seiyuu radio while riding is a game changer. Behold, technology!

Blogging about the blog itself still takes up a sizable portion of my posts (and is a frustratingly self-defeating practice), but I did at least accumulated quite the amount of hoots: these fleeting thoughts aren't organized enough to be its own post, but still interesting enough that I want to write it down. I also use hoots to house my replies to other blogs and the rather cumbersome process of which makes me realize how little I really have to say most of the time. Not to color my still largely manual approach superior, but I do think there is some merit in eliminating low-effort-high-noise contents, both for myself and others.

Ah, donuts, the honey glazed shackles of guilt, the deep-fried cuffs of indulgence. While I would like to attribute this to my will of steel, it is COVID-19 that got the better of such temptations. My laziness and excitement for bunker life eliminated any chances of late night Dunkin' visits. Guess it's time to turn up the dials.

Writing Go was quite the mindless fun exercise. Finding an effective way to learn the C++20 features proved to be harder. =<format>= is the straightforward one and pretty much just works as you'd expect (no compiler supports the standard version yet, so checkout [[https://fmt.dev][the original]]). =<ranges>= is similar to Rust's iterator methods and allows chaining. Maybe I should update my [[/en/posts/2019-04-27-enumerate-with-c-plus-plus/][C++ enumerate() post]]. =<concepts>= seems like the logical solution to the problems SFINAE tried to solve, but I don't have a good context to test out its prowess yet. On a related note, Zig's compile-time function approach to generics is also intriguing.

3 copies, check. 2 different media, check. 1 offsite backup, not yet. I'm also counting Syncthing copies here, and whether they can be relied upon as full fledged backups is debatable. Still some way to go here.

Technically, I did /read/ non-technical books; I just didn't /finish/ any (not counting manga at least). The truth is, aside from those I read purely for entertainment, I am not so sure about what to read. Most non-fiction books look like success stories marinated in flattery and survivor-ship bias, served in sprinkles of anxiety-inducing spices. Fiction works, on the other hand, just doesn't attract me that much: knowing another story to tell just isn't as exciting as learning a new algorithm. Gee that sounded harsh. Do I really think my blog posts fare any better? Anyways, before admitting defeat, I will give this a more serious attempt this year.

*** 2021: Days of Future Past
The ongoing pandemic sparkled nostalgia like never before. People look back at the "normal days" with fondness that I find repulsive. Not to say I'm completely immune to the atmosphere though, just that it rubs me in the opposite way: I find myself grew more assertive than before. After all, doesn't everyone secretly think they are above average and thus know better, especially after reading the news? At the same time, I felt the urge to suppress this feeling before it turns into arrogance, or even worse, ignorance. Perhaps I should learn to let these out in the form of blog posts, like [[https://www.cs.utexas.edu/users/EWD/][EWDs]], just non-technical.

On a positive note, my transition to wake-up-at-5-and-sleep-before-10 schedule is a resounding success. The lockdown actually helped in that I have more leeway to adjust my sleep schedule. Now I have plenty of time for exercise and the option to sleep for up to another two-or-three hours if I'm really pushing it the day before. Given how I clocked in the last 100 miles of rides within the winter holidays, I'll bump the target up this year. 1500 (cycling) miles it is.

After donuts, my challenge this year is to abstain from cookies, which can frequently be found in my work place lunch bags. These piles of butter and sugar are more attractive than I would like to admit at times.

Since I started [[https://beancount.github.io/][beancount]]-ing this year, I'm also looking to applying a similar methodology to managing my time. After Christmas, I've been testing out [[https://www.toggl.com/track/][Toggl Track]] to log how I spend the larger chunks of my time and how many minutes slipped away with me doing nothing. In particular, I figured having a crude "Strava for reading" would make things easier. As for which books to read, I'm thinking classic fictions.

I wonder if this is an age thing: at some point, our auditory perception would just click with the sound of electric guitars, making them impossible to resist. I got an electric guitar now, and I hope to be good enough to play a song or two with it by the end of 2021.

The generation after Z is named [[https://en.wikipedia.org/wiki/Generation_Alpha][Alpha]], which makes no sense at all. To hell with inconsistent naming. To hell with COVID-19 (for different reasons, obviously).

#+begin_quote
  Un de ces matins disparaissent<br/>
  Le soleil brillera toujours.
#+end_quote
