#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: ./
#+HUGO_LEVEL_OFFSET: 1
#+OPTIONS: author:nil
#+STARTUP: logdone

* About
** en
:PROPERTIES:
:EXPORT_TITLE: Library of Trantor
:EXPORT_FILE_NAME: _index.en.md
:END:

#+BEGIN_EXPORT html
<div class="h-card">
<img style="float:right;width:5em;" class="u-photo" alt="" src="/logo.svg">
<h1>Library of Trantor</h1>
#+END_EXPORT

/The [[/en/now/][plan]] needs to go on./

#+BEGIN_EXPORT html
Welcome, wanderer of the Internet. You have stumbled upon the scribbles of one commonly referred to by fellows as <span class="p-nick">shimmy1996</span>, or rather, <a class="u-url u-uid" rel="me" href="https://www.shimmy1996.com/">my blog</a>. "<span class="p-name">Shimmy Xu</span>" is just my <a href="http://stallman.org/biographies.html#humorous%2520bio">mundane name</a>.

Feel free to leave a comment or shoot me an <a rel="me" class="u-email" href="mailto:shimmy.xu%40shimmy1996.com">email</a> directly! Here's my <a class="u-key" rel="pgpkey authn" href="/gpg.txt">PGP key</a> and fingerprint:
#+END_EXPORT

: 5672 AC27 2669 A07A BD28 0896 ACC6 C791 312C F84D

If you are not in a hurry, consider paying a visit to [[/en/friends/][my friends]] as well. If that's not the case, you might find the Library's delivery service (for [[https://www.shimmy1996.com/en/index.xml][timeline]], [[https://www.shimmy1996.com/en/posts/index.xml][posts]], and [[https://www.shimmy1996.com/en/hoots/index.xml][hoots]]) useful.

All contents on this site are licensed under a
[[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-ShareAlike 4.0 International License]] (CC BY-SA 4.0).

#+BEGIN_EXPORT html
</div>
#+END_EXPORT

** zh
:PROPERTIES:
:EXPORT_TITLE: 川陀大学图书室
:EXPORT_FILE_NAME: _index.zh.md
:END:

#+BEGIN_EXPORT html
<div class="h-card">
<img style="float:right;width:5em;" class="u-photo" alt="" src="/logo.svg">
<h1>川陀大学图书室</h1>
#+END_EXPORT

/[[/zh/now/][计划]]进行中。/

#+BEGIN_EXPORT html
欢迎，互联网的游荡者。您偶然发现的这些手记属于传闻中常被称做<span class="p-nick">shimmy1996</span>的个体。换句话说，这里是<a class="u-url u-uid" rel="me" href="https://www.shimmy1996.com/">我的博客</a>。“<span class="p-name">Shimmy Xu</span>”不过是我的<a href="http://stallman.org/biographies.html#humorous%20bio">凡间之名</a>。

留下评论或直接给我发送<a rel="me" class="u-email" href="mailto:shimmy.xu%40shimmy1996.com">电子邮件</a>吧！这是我的<a class="u-key" rel="pgpkey authn" href="/gpg.txt">PGP密匙</a>和指纹：
#+END_EXPORT

: 5672 AC27 2669 A07A BD28 0896 ACC6 C791 312C F84D

如果您不着急离开，不妨也拜访一下我的[[/zh/friends/][朋友们]]。倘若情况正好相反，图书室的送货上门服务（分为[[https://www.shimmy1996.com/zh/index.xml][时间线]]、[[https://www.shimmy1996.com/zh/posts/index.xml][日志]]、和[[https://www.shimmy1996.com/zh/hoots/index.xml][鸮文]]版本）也许能帮到您。

本站所有内容使用[[http://creativecommons.org/licenses/by-sa/4.0/deed.zh][Creative Commons署名-相同方式共享4.0国际许可协议]]（CC BY-SA 4.0）。

#+BEGIN_EXPORT html
</div>
#+END_EXPORT

** ja
:PROPERTIES:
:EXPORT_TITLE: トランター大学図書室
:EXPORT_FILE_NAME: _index.ja.md
:END:

#+BEGIN_EXPORT html
<div class="h-card">
<img style="float:right;width:5em;" class="u-photo" alt="" src="/logo.svg">
<h1>トランター大学図書室</h1>
#+END_EXPORT

/[[/ja/now/][計画]]進行中。/

#+BEGIN_EXPORT html
ようこそ、インターネットの漂泊者よ。あなたの眼の前いる落書きは<span class="p-nick">shimmy1996</span>と謂う個体に所属されているもの。つまり、ここは私のブログ。「<a href="http://stallman.org/biographies.html#humorous%20bio">Shimmy Xu</a>」はただ、私の俗世の名前。

コメントも、<a rel="me" class="u-email" href="mailto:shimmy.xu%40shimmy1996.com">メール</a>も大歓迎です！これは私の<a class="u-key" rel="pgpkey authn" href="/gpg.txt">PGPキー</a>とフィンガープリント：
#+END_EXPORT

: 5672 AC27 2669 A07A BD28 0896 ACC6 C791 312C F84D

急いでいないのなら、私の[[/ja/friends/][友達]]も訪ねてみてください。そうではない場合は、図書室のデリバリーサービス（[[https://www.shimmy1996.com/ja/index.xml][タイムライン]]、[[https://www.shimmy1996.com/ja/posts/index.xml][記事]]と[[https://www.shimmy1996.com/ja/hoots/index.xml][ツイート]]バージョンがあります）をぜひ使ってください。

このサイトのすべてのコンテンツはは[[https://creativecommons.org/licenses/by-sa/4.0/deed.ja][クリエイティブ・コモンズ表示-継承4.0国際ライセンス]]の下に提供されています。

#+BEGIN_EXPORT html
</div>
#+END_EXPORT

* Now
:PROPERTIES:
:EXPORT_HUGO_SLUG: now
:END:

** DONE en
CLOSED: [2020-04-12 Sun 09:46]
:PROPERTIES:
:EXPORT_TITLE: Now
:EXPORT_FILE_NAME: now.en.md
:END:

*** Goals for 2020
- ☐ Run 550 miles. [180/550]
- ☐ Write 14 blog posts. [12/14]
- ☐ No donuts.
- ☐ Dive into Go and C++20. [0/2]
- ☐ Set up proper backup workflow.
- ☐ Read non-technical books.

*** Wishlist
- ☐ Finish a marathon.
- ☐ Get the first signature for my PGP key.
- ☑ Install Gentoo.

** DONE zh
CLOSED: [2020-04-12 Sun 09:46]
:PROPERTIES:
:EXPORT_TITLE: 此刻
:EXPORT_FILE_NAME: now.zh.md
:END:

*** 2020年目标
- ☐ 跑550英里。[180/550]
- ☐ 写14篇日志。[12/14]
- ☐ 不吃甜面包圈。
- ☐ 了解Go和C++20。[0/2]
- ☐ 建立正式的数据备份流程。
- ☐ 阅读非技术类书籍。

*** 愿望清单
- ☐ 完成一次马拉松。
- ☐ 获得第一个PGP密匙签名。
- ☑ 安装Gentoo。

** DONE ja
CLOSED: [2020-04-12 Sun 09:46]
:PROPERTIES:
:EXPORT_TITLE: いま
:EXPORT_FILE_NAME: now.ja.md
:END:

*** 2020年目標
- ☐ 550マイルを走ること。[180/550]
- ☐ 記事14回投稿すること。[6/14]
- ☐ ドーナツを食べるの禁じること。
- ☐ GoとC++20を学びること。[0/2]
- ☐ データバックアップのプロセスを確立すること。
- ☐ 技術類以外の本を読むこと。

*** ウィッシュリスト
- ☐ マラソン完走すろこと。
- ☐ PGPキーの署名をゲットすること。
- ☑ Gentooをインストールすること。

* Friends
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :slug friends
:END:

** en
:PROPERTIES:
:EXPORT_TITLE: Friends
:EXPORT_FILE_NAME: friends.en.md
:END:

#+ATTR_HTML: :alt The Friend Symbol from /20 Century Boys/
[[/img/fixed/friend.svg]]

Welcome to the friendly neighborhood of Library of Trantor!

- [[http://iiiid.com][Z]]
- [[http://uucky.me][Uucky]]
- [[https://tomli.blog][Biergaizi/Tom Li]]
- [[http://a2clef.com][Vacuuny/A2Clef]] as [[http://blog.a2clef.com][himself]]
- [[https://dlyang.me/][LanternD]]

** zh
:PROPERTIES:
:EXPORT_TITLE: 朋友们
:EXPORT_FILE_NAME: friends.zh.md
:END:

#+ATTR_HTML: :alt 《20 世纪少年》中的朋友标志
[[/img/fixed/friend.svg]]

这里会添加朋友们的站点链接！

- [[http://iiiid.com][Z]]
- [[http://uucky.me][Uucky]]
- [[https://tomli.blog][比尔盖子/Tom Li]]
- [[http://a2clef.com][Vacuuny/A2Clef]]的[[http://blog.a2clef.com][里站]]
- [[https://dlyang.me/][LanternD]]

** ja
:PROPERTIES:
:EXPORT_TITLE: 友達
:EXPORT_FILE_NAME: friends.ja.md
:END:

#+ATTR_HTML: :alt 『20世紀少年』のともだちマーク
[[/img/fixed/friend.svg]]

友達サイトへのリンク。

- [[http://iiiid.com][Z]]
- [[http://uucky.me][Uucky]]
- [[https://tomli.blog][Biergaizi/Tom Li]]
- [[http://a2clef.com][Vacuuny/A2Clef]]の[[http://blog.a2clef.com][裏]]
- [[https://dlyang.me/][LanternD]]

* Posts
** en
:PROPERTIES:
:EXPORT_TITLE: Posts
:EXPORT_HUGO_SECTION: ./posts/
:EXPORT_FILE_NAME: _index.en.md
:END:

** zh
:PROPERTIES:
:EXPORT_TITLE: 日志
:EXPORT_HUGO_SECTION: ./posts/
:EXPORT_FILE_NAME: _index.zh.md
:END:

** ja
:PROPERTIES:
:EXPORT_TITLE: 記事
:EXPORT_HUGO_SECTION: ./posts/
:EXPORT_FILE_NAME: _index.ja.md
:END:

* Hoots
** en
:PROPERTIES:
:EXPORT_TITLE: Hoots
:EXPORT_HUGO_SECTION: ./hoots/
:EXPORT_FILE_NAME: _index.en.md
:END:

** zh
:PROPERTIES:
:EXPORT_TITLE: 鸮文
:EXPORT_HUGO_SECTION: ./hoots/
:EXPORT_FILE_NAME: _index.zh.md
:END:

** ja
:PROPERTIES:
:EXPORT_TITLE: ツイート
:EXPORT_HUGO_SECTION: ./hoots/
:EXPORT_FILE_NAME: _index.ja.md
:END:
